MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/EdgeConnectorListener.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/SearchWindowProvider.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/GraphEditorView.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/MaterialGraphView.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/MaterialNodeView.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/ShaderPort.cs
MaterialGraphProject/ProjectSettings/ProjectVersion.txt

* Fixes an issue where edges would get detached from their slots and just hang.
* Introduce a property `MaterialSlot slot` on `ShaderPort`, such that we don't have to access the slot through `userData as MaterialSlot`.
* The `ShaderPort` class now takes care of setting various properties on `Port` based on the given `MaterialSlot`.
When a topological change is triggered, we used to re-create all the UIElements `Port`s in `MaterialNodeView`. Generally it's not bad to just re-create things, but in this case it meant that the edges, which exists outside the scope of a `MaterialNodeView`, would still refer to the old `Port` and through that the old `MaterialSlot`.
Instead, we now update any `Port`s to the newest data if the `id` of the `MaterialSlot` they were holding on to matches a new …

Fix hanging edges (fixes #142, fixes #152, fixes #158)

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/PreviewManager.cs

* Fix a bug where if the user deleted a node or edge and pressed undo, the master preview wouldn't update properly. That is now rectified.

[FIX] Fixed a bug where the master preview didn't update properly after a node got deleted and then undo-ed.

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/GraphEditorView.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/MaterialNodeView.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/PixelCacheProfilerView.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/PixelCacheProfilerView.cs.meta
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/PortInputView.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Resources/Styles/MaterialGraph.uss
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Resources/Styles/PixelCacheProfiler.uss
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Resources/Styles/PixelCacheProfiler.uss.meta
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Resources/UXML/PixelCacheProfiler.uxml
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Resources/UXML/PixelCacheProfiler.uxml.meta

* UI rendering time reduced by roughly half
* Fix bug causing selection outlines to disappear when zoomed out
* Collapsing a node no longer affects controls and preview
There were 2 major culprits wrt. performance. The first was the fact that updating the preview texture would dirty the entire node. This has been fixed by putting the actual texture in its own pixel cached element which floats above the node. The second culprit was the inline inputs, which were being dirtied every frame by the `Attacher`. These have been put into a shared, pixel-cached element per node and the `Attacher` class is no longer used. 
In order to track down the pixel cached elements being dirtied each frame, I wrote a small profiler UI which per frame counts the number of pixel cached elements, how many of them …

Fixes & performance improvements

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/MaterialGraphView.cs

- Fixed an issue causing InvalidOperationException when opening the right-click menu without having a selected node. Now it shows "Open Documentation" menu item only when a single node is selected.
- Changed not to show the separator when the menu item is hidden.

Small fixes to "Open Documentation" menu item.

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/MaterialGraphView.cs

There was an issue that the selection list was not cleared on deletion of nodes. This caused several problems when invoking node-editing actions right after deletion.
e.g. Delete a random node and then open the right click menu without selecting anything. This causes InvalidOperationException in BuildContextualMenu.
This small fix changes the behavior to clear the selection list in the end of the deletion function.

Clear node selection when deleting nodes.

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Range/RandomRangeNode.cs

- Changed the seed input type from Vector1 to Vector2. This makes it handy to generate random noise texture from UV.
- Changed how min/max is applied to random numbers. Although I'm not sure what the original intention was, I think simply lerping from min to max is more natural implementation.

Improvements to RandomRangeNode

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Procedural/Noise/GradientNoiseNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Procedural/Noise/GradientNoiseNode.cs.meta

This pull request is to add GradientNoiseNode that generates 2D gradient noise (generally called "Perlin noise").
Gradient noise is widely used in several DCC software tools to generate procedural textures/animations. Note that it has different characteristics from value noise (used in SimpleNoiseNode). Adding it to the basic node library is thought to be important when we try to make ShaderGraph compatible with commonly-used procedural techniques.

Addition of Gradient Noise node.

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Artistic/Adjustment/ReplaceColorNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Artistic/Blend/BlendNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Artistic/Mask/ColorMaskNode.cs

- Added the Fuzziness slot to ReplaceColorNode and ColorMaskNode. It works like the fuzziness parameter in Photoshop that gives softer edges to the mask.
- Changed the output format of ColorMaskNode from Vector3 to Vector1. It only outputs single channel masks.
- Added the Opacity slot to BlendNode. It's useful when one tries using BlendNode like layers in Photoshop.

Improvements to artistic nodes.

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/ScreenPositionMaterialSlot.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Artistic/Filter/DitherNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/CodeFunctionNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Input/Geometry/ScreenPositionNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Util/ScreenSpaceType.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Util/ScreenSpaceType.cs.meta
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/Slots/ScreenPositionSlotControlView.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/Slots/ScreenPositionSlotControlView.cs.meta
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Resources/Styles/MaterialGraph.uss

In the current version of Shader Graph, there is no custom control view for screen position slots, so users can't simply distinguish them from vector4 slots.
By providing the custom view for the screen position slots, it becomes clear that these slots have different functionalities from simple Vector4 slots or UV slots. It also allows selecting one of the screen space types from the drop down list. This is convenient when using screen space dependent filters like DitherNode.
(UI comparison, left: before / right: after)
**Changes made in this PR**
- Added ScreenPositionSlotControlView and its style element (USS).
- Moved ScreenSpaceType enum definition to ScreenSpaceType.cs and added ScreenSpaceTypeExtensions that provides extension methods for the enum.
- Updated the existing …

Addition of ScreenPositionSlotControlView

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Interfaces/Graph/INode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/AbstractMaterialNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/PreviewManager.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/GraphEditorView.cs

* Replace `onNodeModified` with methods for registering and deregistering to avoid direct access to the delegate.
The reason for this is that calling the delegate directly requires you to check for null, which is easy to forget. Earlier a method `Dirty(ModificationScope)` was added to alleviate this, but `onNodeModified` was still accessible. `Dirty(ModificationScope)` will do the check and is also much more convenient to call:
`if (node.onModified != null) node.onModified(node, ModificationScope.Node)`
vs
`node.Dirty(ModificationScope.Node)`

Safer callbacks

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Interpolation/SmoothstepNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Round/StepNode.cs

The slot names of the Step node are difficult to understand what they're for.
This pull request suggests more easy-to-understand names, following [the GLSL terminology](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/step.xhtml)
Also the slot names of the SmoothStep node are changed.

Easy-to-understand slot names for Step node.

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Inspector/MasterPreviewView.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/PreviewManager.cs

From 2b1bbd8be76c86db5e26f2e65229d4191c47968e, the master preview causes NullReferenceException with the following situations.
- Opening a sub-graph (this is considered to be a showstopper issue).
- Deleting all master nodes from a graph.
This pull request is to fix the problem by adding null check to some points.

Fix for NullReferenceException in master preview.

---

com.unity.shadergraph/Editor/Data/Nodes/Channel/SwizzleNode.cs
com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/ConstantNode.cs
com.unity.shadergraph/Editor/Data/Nodes/Input/Matrix/TransformationMatrixNode.cs
com.unity.shadergraph/Editor/Data/Nodes/Input/PBR/DielectricSpecularNode.cs
com.unity.shadergraph/Editor/Data/Nodes/Input/PBR/MetalReflectanceNode.cs
com.unity.shadergraph/Editor/Drawing/PreviewManager.cs

Fix float serialization in Constant Node to not be affected by system locale (was comma as decimal separator causing shader errors). It's likely that a bunch of other places also need this.

Fix Constant Node code gen

---

com.unity.shadergraph/Editor/Data/Nodes/Procedural/Shape/EllipseNode.cs
com.unity.shadergraph/Editor/Data/Nodes/Procedural/Shape/PolygonNode.cs
com.unity.shadergraph/Editor/Data/Nodes/Procedural/Shape/RectangleNode.cs
com.unity.shadergraph/Editor/Data/Nodes/Procedural/Shape/RoundedRectangleNode.cs

The current implementation of the procedural shape nodes uses the step function to determine the area of the shapes. It causes jaggies (aliasing) on the edges.
These jaggies become more noticeable when using MSAA because these pixel shader-based shapes can't get antialiasing effect from MSAA.
This pull request is to fix the problem by smoothing the edges with using the derivatives (fwidth).

Antialiasing with procedural shapes.

---

com.unity.shadergraph/Editor/Data/LightweightPipeline/LightWeightPBRSubShader.cs
com.unity.shadergraph/Editor/Data/LightweightPipeline/LightWeightUnlitSubShader.cs
com.unity.shadergraph/Editor/Data/MasterNodes/AlphaMode.cs
com.unity.shadergraph/Editor/Data/MasterNodes/PBRMasterNode.cs
com.unity.shadergraph/Editor/Data/MasterNodes/UnlitMasterNode.cs
com.unity.shadergraph/Editor/Data/Util/ShaderGenerator.cs
com.unity.shadergraph/Editor/Templates/lightweightPBRExtraPasses.template
com.unity.shadergraph/Editor/Templates/lightweightUnlitExtraPasses.template

**NOTE**
After discussion with HD team it is incredibly problematic to not have a distinction between opaque and transparent (due to Rough Refraction). In an effort for some unification between pipelines I have split the blend enum and renamed the entries to match theirs. Lightweight may also need to split, or just match mode namings.
- Split Blend enum into Surface and Blend enums
- Add two sided option to PBR and Unlit master nodes
- Add culling control to shadow pass (allow two sided shadow casting)
- Add Transparent (pre multuply alpha) blend mode
- Add Multiply blend mode
- Rename blend modes (AlphaBlend > Fade, AdditiveBlend > Additive)
- Add labels to Workflow and Blending dropdowns

Master node improvements

---

com.unity.shadergraph/Editor/Drawing/Inspector/MasterPreviewView.cs
com.unity.shadergraph/Editor/Drawing/Manipulators/ResizeSideHandle.cs
com.unity.shadergraph/Editor/Drawing/Manipulators/WindowDraggable.cs
com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs

Reflect rename in future Unity versions of class PostLayoutEvent to GeometryChangedEvent (with fallback import for 2018.1). This gets us 1 step closer to compiling on trunk.

PostLayoutEvent -> GeometryChangedEvent

---

com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs
com.unity.shadergraph/Editor/Drawing/Views/PortInputView.cs

Making sure that the inputs on a referenced subgraph is editable at all times. 
Fix the issue that when saving a subgraph the link to the input container got lost and the user couldn't any longer change the default values inside the shader graph without reopening the shader graph.

Fix for issue #271

---

com.unity.shadergraph/Editor/Templates/HDUnlitPassForward.template

In 1.0.0-beta, the following error occurs with any unlit graph.
```
Assertion failed: Assertion failed on expression: 'success'
UnityEditor.ShaderUtil:CreateShaderAsset(String)
ShaderGraphImporter:OnImportAsset(AssetImportContext)
...
```
From further investigation, I found `IsGammaSpace()` is undefined in the HD Unlit subshader.
This pull request is to fix the problem by simply adding `#include` to the shader template.

Fix: IsGammaSpace is undefined in the HD Unlit subshader

---

com.unity.shadergraph/Editor/Data/Graphs/SerializableCubemap.cs
com.unity.shadergraph/Editor/Data/Graphs/SerializableMesh.cs
com.unity.shadergraph/Editor/Data/Graphs/SerializableTexture.cs

Fix warnings from about unused variables that are kept there for legacy deserialization

Fix warnings from legacy deserialization classes

---

com.unity.shadergraph/Editor/Drawing/Controls/ChannelEnumControl.cs
com.unity.shadergraph/Editor/Drawing/Controls/ChannelEnumMaskControl.cs
com.unity.shadergraph/Editor/Resources/Styles/Controls/ChannelEnumControlView.uss
com.unity.shadergraph/Editor/Resources/Styles/Controls/ChannelEnumControlView.uss.meta
com.unity.shadergraph/Editor/Resources/Styles/Controls/ChannelEnumMaskControlView.uss
com.unity.shadergraph/Editor/Resources/Styles/Controls/ChannelEnumMaskControlView.uss.meta

Updated the ChannelEnum and ChannelEnumMask controls to use their own uss files. This solves the 5pixels extra width on the nodes using them.

[FIX] # 288

---

com.unity.shadergraph/Editor/Data/Graphs/AbstractMaterialGraph.cs
com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs
com.unity.shadergraph/Editor/Drawing/SearchWindowProvider.cs
com.unity.shadergraph/Editor/Importers/ShaderGraphImporter.cs

Enables the user to change the path of Shader Graphs and Sub Graphs as requested in issue #289. Changing the path of a Shader Graph modifies the location it has in the shader selection list. Likewise changing the path of Sub Graph modifies its location in the node creation menu.

Change path for graphs

---

com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs

Replacing soon-to-be deprecated API Resources.Load(string) for Resources.Load<T>(string)

Update deprecated Resources API

---

com.unity.shadergraph/Editor/Drawing/Controls/ChannelEnumControl.cs
com.unity.shadergraph/Editor/Resources/Styles/Controls/ChannelEnumControlView.uss

Minor PR. Updates the ChannelEnumControl to use `PopupField` from UIElements instead of the old `EditorGUILayout.Popup`.
Some things to note:
- Have to recreate the popup field every time the node or the control are modified.
- This control now suffers the same lack of update response when changing input connections (see https://favro.com/card/c564ede4ed3337f7b17986b6/Uni-37652)

Update ChannelEnumControl to UIElements and USS

---

com.unity.shadergraph/Editor/Drawing/Manipulators/Draggable.cs
com.unity.shadergraph/Editor/Drawing/Manipulators/ResizeSideHandle.cs
com.unity.shadergraph/Editor/Drawing/Manipulators/WindowDraggable.cs
com.unity.shadergraph/Editor/Util/CompatibilityExtensions.cs

Capturemouse event and trickle down enum has changed and this is a fix for that so it is compatible with older versions.

Fix obsolete warnings

---

CHANGELOG.md
com.unity.shadergraph/Editor/Data/Graphs/SerializableGuid.cs
com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
com.unity.shadergraph/Editor/Drawing/Views/MaterialGraphView.cs
com.unity.shadergraph/Editor/Util/CopyPasteGraph.cs

Makes copied nodes spawn in the center of the current view when copied from another graph.
This fixes #333

Node placement copy

---

com.unity.shadergraph/Editor/Drawing/SearchWindowProvider.cs

This PR fixes an issue introduced with editable sub graph paths, causing the search window to sometimes yield a null reference exception.

Fix null refs in search window provider
