MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/DynamicVectorMaterialSlot.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/SerializableCubemap.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/SerializableTexture.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/Vector1MaterialSlot.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/Vector2MaterialSlot.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/Vector3MaterialSlot.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/Vector4MaterialSlot.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Implementation/NodeUtils.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Input/Basic/Vector1Node.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Input/Basic/Vector2Node.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Input/Basic/Vector3Node.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Input/Basic/Vector4Node.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/MaterialGraphEditWindow.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Importers/ShaderGraphImporter.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Resources/Styles/MaterialGraph.uss

Hi Peter, Could you please review these fixes for me?

Fixes for bugs 

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/LightweightPipeline/LightWeightPBRSubShader.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/LightweightPipeline/LightWeightUnlitSubShader.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/MasterNodes/PBRMasterNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/MasterNodes/UnlitMasterNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/AbstractMaterialNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/MasterNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Util/GraphUtil.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Util/ShaderGenerator.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/PreviewManager.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/PreviewSceneResources.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Resources/Shaders/BlitNoAlpha.shader
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Resources/Shaders/BlitNoAlpha.shader.meta
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Templates/lightweightPBRForwardPass.template
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Templates/lightweightUnlitPass.template

Cases referenced in the commit message.

Misc bug fixes

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Input/Geometry/ScreenPositionNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Input/Scene/FogNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Vector/TransformNode.cs

- Add a frac to Tile mode of Screen Position
- Updates to latest SRP library (Transform node, Fog node)

Node bugfixes

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/AbstractMaterialGraph.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Blackboard/BlackboardField.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Blackboard/BlackboardProvider.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Blackboard/BlackboardSection.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Manipulators/GraphDropTarget.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/MaterialGraphView.cs

* Adds support for reordering properties in blackboard
* Adds support for drag and dropping properties to the graph

Blackboard improvements

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/ScreenPositionMaterialSlot.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Artistic/Filter.meta
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Artistic/Filter/DitherNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Artistic/Filter/DitherNode.cs.meta
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Input/Geometry/ScreenPositionNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Input/PBR.meta
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Input/PBR/DielectricSpecularNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Input/PBR/DielectricSpecularNode.cs.meta
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Input/PBR/MetalReflectanceNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Input/PBR/MetalReflectanceNode.cs.meta
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/UV/TriplanarNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/UV/TriplanarNode.cs.meta
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Controls/DielectricSpecularControl.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Controls/DielectricSpecularControl.cs.meta
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Resources/Styles/MaterialGraph.uss

New Nodes:
- Metal Reflectance
- Dielectric Specular
- Triplanar
- Dither
New Controls Views:
- Dielectric Specular

Various nodes

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Blackboard/BlackboardField.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Blackboard/BlackboardProvider.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Manipulators/WindowDraggable.cs

* Adds undo actions for blackboard things (I forgot to add this previously)
* Blackboard can now only be dragged using the header in order to avoid conflicts with fields

Fixes for blackboard

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/UVMaterialSlot.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/PreviewManager.cs

* Fixed a bug causing previews to not use the correct preview mode (2D/3D)
* Fixed a bug causing inline UV channel to not be serialized

Various fixes

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/MaterialNodeView.cs

* Adds a change in width when the preview node is resized

Make preview node change in width on resizing (fixes #121)

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Inspector/MasterPreviewView.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Resources/Styles/MaterialGraph.uss

Fixed the overall look to look more like the other nodes.
Removed Header
Removed the bottom Mesh Picker.
Added right click context menu for selecting Mesh
Rounded Corners.
-------
Uni-36221

Tidied up the Master Preview View

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/MaterialGraphView.cs

Added right click menu to Collapse and Expand Previews in MaterialGraphView

Collapse and Expand Previews for Material Graph

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/AbstractMaterialNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Advanced/AbsoluteNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Advanced/ExponentialNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Advanced/LengthNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Advanced/LogNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Advanced/ModuloNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Advanced/NegateNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Advanced/NormalizeNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Advanced/PosterizeNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Advanced/ReciprocalNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Advanced/ReciprocalSquareRootNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Basic/AddNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Basic/DivideNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Basic/MultiplyNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Basic/PowerNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Basic/SquareRootNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Nodes/Math/Basic/SubtractNode.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/GraphEditorView.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/MaterialGraphView.cs

public virtual string documentationURL()   has been added to AbstractMaterialNode
Pressing F1 will take you to the documentation if it exists.
Right clicking on a node gives you the context menu item See Documentation that also takes you to the documentation if it exists.

Adding documentation functionality on the nodes.

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/AbstractMaterialGraph.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Inspector/MasterPreviewView.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Manipulators/Scrollable.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Manipulators/Scrollable.cs.meta
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/PreviewManager.cs

* Add scrollable manipulator
* Add scale field to preview data

Master preview zoom

---

.gitignore
MaterialGraphProject/Assets/UnityShaderEditor/.npmignore
build.py

Adding automation to the package
- Adding new directories to ignore (artifacts and build)
- New build.py that assumes presence of the automation-tools repo to be able to build the package and run various tests

Build automation

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/Vector2ShaderProperty.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/Vector3ShaderProperty.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/Vector4ShaderProperty.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Data/Graphs/VectorShaderProperty.cs

Changed to use correct dimensions in declarations of properties.

Fix for issue #222

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Blackboard/BlackboardProvider.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Manipulators/ResizeSideHandle.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Manipulators/WindowDraggable.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Views/GraphEditorView.cs

* Split resize functions in ResizeSideHandle into one function for each direction. this allows handling of each resize direction separately.

Master preview rendertexture rescale

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/Inspector/MasterPreviewView.cs

* Setting master preview dirty after zoom changes
* Make master preview dirty after render texture refresh (fixes #235)
* Add hide flags to master preview render texture (fixes #255)

Master preview missing RenderTexture fixes

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/MaterialGraphEditWindow.cs
MaterialGraphProject/Assets/UnityShaderEditor/Editor/Importers/ShaderGraphImporterEditor.cs

* Fixes an issue where new windows did not adjust the zoom level

Fixes #242 by initalizing the color space field properly

---

MaterialGraphProject/Assets/UnityShaderEditor/Editor/Drawing/PreviewManager.cs
MaterialGraphProject/ProjectSettings/ProjectSettings.asset

* Adds a define to the Shader Graph project so that we can hide debuggy stuff behind #ifdefs (in this case shader recreation logging and GeneratedShader+UberShader files)

Devmode define

---

com.unity.shadergraph/Editor/Data/Nodes/Math/Vector/DotProductNode.cs
com.unity.shadergraph/Editor/Data/Nodes/Utility/Logic/BranchNode.cs

- Update Dot Product to use Dynamic Vectors
- Change Branch evaluation to lerp

Minor node fixes

---

com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
com.unity.shadergraph/Editor/Drawing/Controls/IntegerControl.cs
com.unity.shadergraph/Editor/Drawing/Controls/ToggleControl.cs
com.unity.shadergraph/Editor/Util/CompatibilityExtensions.cs

Should work with both 2018.1 and trunk

More trunk compatibility fixes

---

com.unity.shadergraph/Editor/Data/Graphs/ColorMaterialSlot.cs
com.unity.shadergraph/Editor/Data/Graphs/ColorRGBMaterialSlot.cs
com.unity.shadergraph/Editor/Data/Graphs/DynamicValueMaterialSlot.cs
com.unity.shadergraph/Editor/Data/Graphs/DynamicVectorMaterialSlot.cs
com.unity.shadergraph/Editor/Data/Graphs/MaterialSlot.cs
com.unity.shadergraph/Editor/Data/Graphs/ScreenPositionMaterialSlot.cs
com.unity.shadergraph/Editor/Data/Graphs/SpaceMaterialSlot.cs
com.unity.shadergraph/Editor/Data/Graphs/UVMaterialSlot.cs
com.unity.shadergraph/Editor/Data/Graphs/Vector1MaterialSlot.cs
com.unity.shadergraph/Editor/Data/Graphs/Vector1ShaderProperty.cs
com.unity.shadergraph/Editor/Data/Graphs/Vector2MaterialSlot.cs
com.unity.shadergraph/Editor/Data/Graphs/Vector2ShaderProperty.cs
com.unity.shadergraph/Editor/Data/Graphs/Vector3MaterialSlot.cs
com.unity.shadergraph/Editor/Data/Graphs/Vector3ShaderProperty.cs
com.unity.shadergraph/Editor/Data/Graphs/Vector4MaterialSlot.cs
com.unity.shadergraph/Editor/Data/Graphs/Vector4ShaderProperty.cs
com.unity.shadergraph/Editor/Data/Graphs/VertexColorMaterialSlot.cs
com.unity.shadergraph/Editor/Data/Interfaces/IMayRequirePosition.cs
com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/Vector1Node.cs
com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/Vector2Node.cs
com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/Vector3Node.cs
com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/Vector4Node.cs
com.unity.shadergraph/Editor/Data/Nodes/SlotValue.cs
com.unity.shadergraph/Editor/Drawing/Views/Slots/MultiFloatSlotControlView.cs

Added input fields for Vector 1,2,3,4. Now they look and behave like other nodes.
Also added Labels functionality on the input fields so that we can label them with what we want.
Also made IMayRequirePosition public. This came from a user. And will close #292

Vector input fields and IMayRequirePosition

---

com.unity.shadergraph/Editor/Drawing/Blackboard/Blackboard.cs
com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs
com.unity.shadergraph/Editor/Drawing/Inspector/MasterPreviewView.cs
com.unity.shadergraph/Editor/Drawing/Inspector/WindowDockingLayout.cs
com.unity.shadergraph/Editor/Drawing/Manipulators/ResizeBorderFrame.cs
com.unity.shadergraph/Editor/Drawing/Manipulators/ResizeSideHandle.cs
com.unity.shadergraph/Editor/Drawing/Manipulators/WindowDraggable.cs
com.unity.shadergraph/Editor/Drawing/Views/GraphEditorView.cs
com.unity.shadergraph/Editor/Resources/Styles/Blackboard.uss
com.unity.shadergraph/Editor/Resources/Styles/GraphEditorView.uss
com.unity.shadergraph/Editor/Resources/Styles/MasterPreviewView.uss

* Change ResizeHandle and WindowDraggable to use absolute positioning instead of manuel positioning.
* Make master preview render texture re-scale continuously when resized.
* Add collapse button to master preview.

Layout modifiers improvements

---

com.unity.shadergraph/Editor/Data/Graphs/AbstractMaterialGraph.cs
com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs

Made sure you cannot have empty strings as property names.
Also added functionality so that you cannot have properties with the same name. It appends (*) to your property where * is just the next sequential number.

Blackboard Property fixes.

---

com.unity.shadergraph/Editor/Data/Graphs/Vector4MaterialSlot.cs
com.unity.shadergraph/Editor/Data/SubGraph/SubGraphOutputNode.cs
com.unity.shadergraph/Editor/Data/Util/GraphUtil.cs
com.unity.shadergraph/Editor/Drawing/Inspector/MasterPreviewView.cs
com.unity.shadergraph/Editor/Drawing/PreviewManager.cs

* Add input slots on output node in sub-graph.
* Make the output nodes in sub-graphs have 3D preview similar to the master nodes.

Sub graph preview fix

---

com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardProvider.cs
com.unity.shadergraph/Editor/Drawing/SearchWindowProvider.cs

This PR removes some uses of .NET 4+ only API that snuck into `master` recently. A backport will be needed if the PRs that introduced the uses needs backporting.

Fix legacy scripting backend compatibility

---

com.unity.shadergraph/Editor/Data/Graphs/DynamicVectorMaterialSlot.cs
com.unity.shadergraph/Editor/Data/Implementation/NodeUtils.cs

Fixes for decimal issues. comma and period could be wrong / different on different machines, this PR should fix that.

Fix for issues regarding decimals / periods

---

HDPipeline/HDRPInterpolators.cs

Small fix for screenposition interpolator.

screenPosition should be a vector 4

---

com.unity.shadergraph/Editor/Data/Nodes/Input/Basic/Vector1Node.cs

FIX #337 
Before this fix the node returned at generationMode.IsPreview() and didn't use the input properly.

Fixed an issue where vector 1 node was not evaluating properly.

---

com.unity.shadergraph/Editor/Drawing/Views/MaterialNodeView.cs

This PR adds a change callback to controls when a connected edge changes.

Callback on edge change to ControlView

---

com.unity.shadergraph/Editor/Drawing/Blackboard/BlackboardFieldPropertyView.cs
com.unity.shadergraph/Editor/Resources/Styles/Blackboard.uss
com.unity.shadergraph/Editor/Resources/Styles/ShaderGraphBlackboard.uss
com.unity.shadergraph/Editor/Resources/Styles/ShaderGraphBlackboard.uss.meta

Added .uss file for making fonts and other properties display correctly

Fix font sizes in blackboard

---

com.unity.shadergraph/Editor/Data/Nodes/Procedural/CheckerboardNode.cs

AA settings were pretty messed up and not doing anything..  re-tweaked, and switched to a better frequency limiter to get rid of residual high frequency aliasing.

Fixing AA of procedural checkerboard node
